PYTHON_DJANGO/django_devsns_project/devsns/devsns/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from snsapp import views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('postcreate',views.postcreate, name='postcreate'),
    path('detail/<int:post_id>',views.detail, name='detail'),
    path('new_comment/<int:post_id>',views.new_comment, name='new_comment'),
    
    path('login/',accounts_views.login, name='login'),
    path('logout/',accounts_views.logout, name='logout'),
    path('signup/',accounts_views.signup, name='signup'),


    path('freehome',views.freehome, name='freehome'),
    path('freepostcreate',views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>',views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>',views.new_freecomment, name='new_freecomment'),
]

PYTHON_DJANGO/django_devsns_project/devsns/accounts/models.py
from django.db import models

# Create your models here.

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/models.py
from turtle import title
from django.db import models

from django.contrib.auth.models import User

# 익명게시판
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    # 객체 추가될 때마다 그 당시의 시간대 자동저장
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# ORM : 클래스를 이용해 db에 맵핑하는 모델
class Comment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comment

# 자유게시판
class FreePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    # 객체 추가될 때마다 그 당시의 시간대 자동저장
    date = models.DateTimeField(auto_now_add=True)
    # 작성자 => 장고에 내장된 User 객체를 참조해야.
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title    

class FreeComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(FreePost, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comment

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/forms.py
from django import forms
from .models import *


class Postform(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class Commentform(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        fields = ['comment']


class FreePostform(forms.ModelForm):
    class Meta:
        model = FreePost
        fields = ['title', 'body']


class FreeCommentform(forms.ModelForm):
    class Meta:
        model = FreeComment
        # fields = '__all__'
        fields = ['comment']

PYTHON_DJANGO/django_devsns_project/devsns/accounts/views.py
from django.shortcuts import redirect, render

# 로그인 기능 위해
from django.contrib import auth
# 회원가입 위해 User 객체 필요
from django.contrib.auth.models import User

def login(request):
    # POST 면 로그인 요청
    if request.method == "POST":
        userid = request.POST['username']
        userpwd = request.POST['password']

        user = auth.authenticate(request, username=userid, password=userpwd)

        if user is not None:
            auth.login(request, user)
            return redirect('home')

        else:
            return render(request, 'bad_login.html')

    # GET 이면 로그인하는 html 띄우기.
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('home')


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        password1 = request.POST['password']
        password2 = request.POST['repeat']

        if password1 == password2:
            # 회원가입 ; 새로운 user 객체 생성
            new_user = User.objects.create_user(
                username = username, password=password1
            )
            # 로그인
            auth.login(request, new_user)
            # 홈으로 리다이렉션
            return redirect('home')
    else:
        return render(request, 'register.html')

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/views.py
from django.shortcuts import redirect, render,get_object_or_404

from .forms import *
from .models import *
# Create your views here.

def home(request):
    # 홈에 글들의 목록을 띄워주기 위해 글 객체들 불러오기
    # posts = Post.objects.all()
    posts = Post.objects.filter().order_by('-date')

    return render(request, 'index.html', {'posts':posts})

    # 공통부분은 base.html 에 담아 상속받아 재사용하기

# 쟝고는 한 url 안에 post와 get 모두 처리가능.
def postcreate(request):
    # post 요청이면 입력값 저장
    if request.method == "POST" or request.method == 'FILES':
        # POST요청 들어온 거 폼에 다 담고
        form = Postform(request.POST, request.FILES)

        # form 유효성 검사
        if form.is_valid():
            # 모델form은 save()매서드가 있어서 바로 저장.
            form.save()
            return redirect('home')
        
    
    # get 요청이면 입력 html 띄우기
    else:
        form = Postform()
    return render(request, 'post_form.html', {'form':form})

def detail(request, post_id):
    # post = Post.objects.filter(pk=post_id)
    post_detail = get_object_or_404(Post, pk=post_id)
    comment_form = Commentform()

    return render(request, 'detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

# 댓글저장
def new_comment(request, post_id):
    # POST요청 받은 거 담고
    filled_form = Commentform(request.POST)
    # 유효한지 검사하고
    if filled_form.is_valid():
        # 바로 저장하면 안되고 
        # 꼭 넣어줘야하는 정보인데 아직 넣지 않은 정보; 어떤 게시물의 댓글인지에 대한 FK정보도 넣어주기.
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.save()
        # detail페이지인데 내가 댓글 단 페이지(post_id)도 같이 명시
        return redirect('detail', post_id)


def freehome(request):
    # 홈에 글들의 목록을 띄워주기 위해 글 객체들 불러오기
    # posts = Post.objects.all()
    freeposts = FreePost.objects.filter().order_by('-date')

    return render(request, 'free_index.html', {'freeposts':freeposts})

# 쟝고는 한 url 안에 post와 get 모두 처리가능.
def freepostcreate(request):
    # post 요청이면 입력값 저장
    if request.method == "POST" or request.method == 'FILES':
        # POST요청 들어온 거 폼에 다 담고
        form = FreePostform(request.POST, request.FILES)

        # form 유효성 검사
        if form.is_valid():
            # 모델form은 save()매서드가 있어서 바로 저장.
            unfinished_form = form.save(commit=False)
            unfinished_form.author = request.user
            unfinished_form.save()
            return redirect('freehome')
        
    # get 요청이면 입력 html 띄우기
    else:
        form = FreePostform()
    return render(request, 'free_post_form.html', {'form':form})

def freedetail(request, post_id):
    # post = Post.objects.filter(pk=post_id)
    post_detail = get_object_or_404(FreePost, pk=post_id)
    comment_form = FreeCommentform()

    return render(request, 'free_detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

# 댓글저장
def new_freecomment(request, post_id):
    # POST요청 받은 거 담고
    filled_form = FreeCommentform(request.POST)
    # 유효한지 검사하고
    if filled_form.is_valid():
        # 바로 저장하면 안되고 
        # 꼭 넣어줘야하는 정보인데 아직 넣지 않은 정보; 어떤 게시물의 댓글인지에 대한 FK정보도 넣어주기.
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(FreePost, pk=post_id)
        finished_form.save()
        # detail페이지인데 내가 댓글 단 페이지(post_id)도 같이 명시
        return redirect('freedetail', post_id)

PYTHON_DJANGO/django_devsns_project/devsns/accounts/templates/bad_login.html
존재하지 않는 회원입니다.
<br />
<a href="{% url 'login' %}">다시 로그인</a>

PYTHON_DJANGO/django_devsns_project/devsns/accounts/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>

  <body class="bg-gradient-primary">
    <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                    </div>
                    <form class="user" method="POST">
                        {% csrf_token%}
                      <div class="form-group">
                        <input
                          type="text"
                          class="form-control form-control-user"
                          id="username"
                          name="username"
                          aria-describedby="emailHelp"
                          placeholder="Enter Email Address..."
                        />
                      </div>
                      <div class="form-group">
                        <input
                          type="password"
                          class="form-control form-control-user"
                          id="password"
                          name="password"
                          placeholder="Password"
                        />
                      </div>
                      <div class="form-group">
                        <div class="custom-control custom-checkbox small">
                          <input
                            type="checkbox"
                            class="custom-control-input"
                            id="customCheck"
                          />
                        </div>
                      </div>
                    
                        <input type="submit" value="login" class="btn btn-primary btn-user btn-block"/>
                        Login
                      </a>
                      <hr />
                    </form>

                    <div class="text-center">
                      <a class="small" href="{% url 'signup'%}"
                        >Create an Account!</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  </body>
</html>

PYTHON_DJANGO/django_devsns_project/devsns/accounts/templates/register.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>

  <body class="bg-gradient-primary">
    <div class="container">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                </div>
                <form class="user" method="POST">
                    {% csrf_token %}
                  <div class="form-group row"></div>
                  <div class="form-group">
                    <input
                      type="text"
                      name="username"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      placeholder="User Name"
                    />
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <input
                        type="password"
                        name="password"
                        class="form-control form-control-user"
                        id="exampleInputPassword"
                        placeholder="Password"
                      />
                    </div>
                    <div class="col-sm-6">
                      <input
                        type="password"
                        name="repeat"
                        class="form-control form-control-user"
                        id="exampleRepeatPassword"
                        placeholder="Repeat Password"
                      />
                    </div>
                  </div>
                  <input type="submit" value="회원가입" class="btn btn-primary btn-user btn-block">
                  
                    Register Account
                  </a>
                  <hr />
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'login' %}"
                    >Already have an account? Login!</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb -admin-2.min.js' %}"></script>
  </body>
</html>

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>개발자 대나무숲</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="{% url 'freehome' %}"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">개발자 대나무숲</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'freehome' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider" />

        <!-- Heading -->
        <div class="sidebar-heading">Interface</div>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>익명게시판</span></a
          >
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'freehome' %}">
            <i class="fas fa-fw fa-table"></i>
            <span>자유게시판</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="searchDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div
                  class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                  aria-labelledby="searchDropdown"
                >
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input
                        type="text"
                        class="form-control bg-light border-0 small"
                        placeholder="Search for..."
                        aria-label="Search"
                        aria-describedby="basic-addon2"
                      />
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  {% if user.is_authenticated %}
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >{{user.username}}</span
                  >
                  {% else %}
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >로그인</span
                  >
                  {% endif %}
                  <img
                    class="img-profile rounded-circle"
                    src="{% static 'img/undraw_profile.svg' %}"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                  aria-labelledby="userDropdown"
                >
                  {% if user.is_authenticated %}
                  <div class="dropdown-divider"></div>
                  <a
                    class="dropdown-item"
                    href="{% url 'logout' %}"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Logout
                  </a>
                  {% else %}
                  <a class="dropdown-item" href="{% url 'login' %}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Login
                  </a>
                  {% endif %}
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">{% block content %} {% endblock %}</div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2022</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              로그아웃하시겠어요?
            </h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">아래 로그아웃 버튼을 눌러주세요.</div>
          <div class="modal-footer">
            <a class="btn btn-success" href="{% url 'logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
  </body>
</html>

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/templates/free_detail.html
{% extends 'base.html' %} {% block content%}
<h1>상세페이지</h1>
<h2>제목 : {{post_detail.title}}</h2>
<h2>작성날짜 : {{post_detail.date}}</h2>

<p>{{post_detail.body}}</p>

<!-- 댓글 목록 -->
<!-- 중요. post_detail(특정 pk값으로 가져온 객체)를 참고하고 있는 객체들(comment_set) 전부가져오기. -->
{% for comment in post_detail.freecomment_set.all %}
<p>
{{ comment}}
<hr>
</p>
{% endfor %}

<!-- 댓글 입력공간 -->
<form action="{%url 'new_freecomment' post_detail.id %}" method="POST">
  {% csrf_token %}
  <table>
    {{ comment_form.as_table }}
    
  </table>
  <input type="submit" value="댓글 작성" />
</form>

{% endblock %}

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/templates/free_post_form.html
{% extends 'base.html'%} {% block content%}

<h1>새글 작성</h1>
<form
  action="{% url 'freepostcreate' %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <!-- 모델폼 같은 경우에는 어떤 형태로 form을 보여줄지도 나타낼 수 있다. -->
  <!-- 예를 들어  -->
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="새글 생성 " />
</form>
{% endblock%}

PYTHON_DJANGO/django_devsns_project/devsns/snsapp/templates/post_form.html
{% extends 'base.html'%} {% block content%}

<h1>새글 작성</h1>
<form
  action="{% url 'postcreate' %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <!-- 모델폼 같은 경우에는 어떤 형태로 form을 보여줄지도 나타낼 수 있다. -->
  <!-- 예를 들어  -->
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="새글 생성 " />
</form>
{% endblock%}